python3 time_entropy_2.py -png   1.png --full True -f MTX/Rucci1.mtx
python3 time_entropy_2.py -png   2.png --full True -f MTX/sls.mtx
python3 time_entropy_2.py -png   3.png --full True -f MTX/ESOC.mtx
python3 time_entropy_2.py -png   4.png --full True -f MTX/offshore.mtx
python3 time_entropy_2.py -png   5.png --full True -f MTX/torso3.mtx
python3 time_entropy_2.py -png   6.png --full True -f MTX/Lin.mtx
python3 time_entropy_2.py -png   7.png --full True -f MTX/BenElechi1.mtx
python3 time_entropy_2.py -png   8.png --full True -f MTX/patents_main.mtx
python3 time_entropy_2.py -png   9.png --full True -f MTX/Si87H76.mtx
python3 time_entropy_2.py -png  10.png --full True -f MTX/image_interp.mtx
python3 time_entropy_2.py -png  11.png --full True -f MTX/mesh_deform.mtx
python3 time_entropy_2.py -png  12.png --full True -f MTX/bmw3_2.mtx
python3 time_entropy_2.py -png  13.png --full True -f MTX/HTC_336_9129.mtx
python3 time_entropy_2.py -png  14.png --full True -f MTX/HTC_336_4438.mtx
python3 time_entropy_2.py -png  15.png --full True -f MTX/CO.mtx
python3 time_entropy_2.py -png  16.png --full True -f MTX/hood.mtx
python3 time_entropy_2.py -png  17.png --full True -f MTX/pwtk.mtx
python3 time_entropy_2.py -png  18.png --full True -f MTX/stomach.mtx
python3 time_entropy_2.py -png  19.png --full True -f MTX/mac_econ_fwd500.mtx
python3 time_entropy_2.py -png  20.png --full True -f MTX/thermomech_dM.mtx
python3 time_entropy_2.py -png  21.png --full True -f MTX/thermomech_dK.mtx
python3 time_entropy_2.py -png  22.png --full True -f MTX/turon_m.mtx
python3 time_entropy_2.py -png  23.png --full True -f MTX/hvdc2.mtx
python3 time_entropy_2.py -png  24.png --full True -f MTX/Si41Ge41H72.mtx
python3 time_entropy_2.py -png  25.png --full True -f MTX/d_pretok.mtx
python3 time_entropy_2.py -png  26.png --full True -f MTX/ohne2.mtx
python3 time_entropy_2.py -png  27.png --full True -f MTX/cont-300.mtx
python3 time_entropy_2.py -png  28.png --full True -f MTX/shipsec5.mtx
python3 time_entropy_2.py -png  29.png --full True -f MTX/transient.mtx
python3 time_entropy_2.py -png  30.png --full True -f MTX/scircuit.mtx
python3 time_entropy_2.py -png  31.png --full True -f MTX/c-73b.mtx
python3 time_entropy_2.py -png  32.png --full True -f MTX/c-73.mtx
python3 time_entropy_2.py -png  33.png --full True -f MTX/PR02R.mtx
python3 time_entropy_2.py -png  34.png --full True -f MTX/majorbasis.mtx
python3 time_entropy_2.py -png  35.png --full True -f MTX/crashbasis.mtx
python3 time_entropy_2.py -png  36.png --full True -f MTX/xenon2.mtx
python3 time_entropy_2.py -png  37.png --full True -f MTX/para-5.mtx
python3 time_entropy_2.py -png  38.png --full True -f MTX/para-9.mtx
python3 time_entropy_2.py -png  39.png --full True -f MTX/para-10.mtx
python3 time_entropy_2.py -png  40.png --full True -f MTX/para-8.mtx
python3 time_entropy_2.py -png  41.png --full True -f MTX/para-7.mtx
python3 time_entropy_2.py -png  42.png --full True -f MTX/para-6.mtx
python3 time_entropy_2.py -png  43.png --full True -f MTX/SiO2.mtx
python3 time_entropy_2.py -png  44.png --full True -f MTX/para-4.mtx
python3 time_entropy_2.py -png  45.png --full True -f MTX/G2_circuit.mtx
python3 time_entropy_2.py -png  46.png --full True -f MTX/bmwcra_1.mtx
python3 time_entropy_2.py -png  47.png --full True -f MTX/FEM_3D_thermal2.mtx
python3 time_entropy_2.py -png  48.png --full True -f MTX/Dubcova3.mtx
python3 time_entropy_2.py -png  49.png --full True -f MTX/bmw7st_1.mtx
#python3 time_entropy_2.py -png  50.png --full True -f MTX/shipsec1.mtx
#python3 time_entropy_2.py -png  51.png --full True -f MTX/Ga19As19H42.mtx
#python3 time_entropy_2.py -png  52.png --full True -f MTX/cage12.mtx
#python3 time_entropy_2.py -png  53.png --full True -f MTX/boneS01.mtx
#python3 time_entropy_2.py -png  54.png --full True -f MTX/matrix-new_3.mtx
#python3 time_entropy_2.py -png  55.png --full True -f MTX/cfd2.mtx
#python3 time_entropy_2.py -png  56.png --full True -f MTX/ship_003.mtx
#python3 time_entropy_2.py -png  57.png --full True -f MTX/cop20k_A.mtx
#python3 time_entropy_2.py -png  58.png --full True -f MTX/twotone.mtx
#python3 time_entropy_2.py -png  59.png --full True -f MTX/TSOPF_FS_b39_c30.mtx
#python3 time_entropy_2.py -png  60.png --full True -f MTX/dc3.mtx
#python3 time_entropy_2.py -png  61.png --full True -f MTX/dc1.mtx
#python3 time_entropy_2.py -png  62.png --full True -f MTX/trans4.mtx
#python3 time_entropy_2.py -png  63.png --full True -f MTX/trans5.mtx
#python3 time_entropy_2.py -png  64.png --full True -f MTX/dc2.mtx
#python3 time_entropy_2.py -png  65.png --full True -f MTX/torso1.mtx
#python3 time_entropy_2.py -png  66.png --full True -f MTX/torso2.mtx
#python3 time_entropy_2.py -png  67.png --full True -f MTX/barrier2-12.mtx
#python3 time_entropy_2.py -png  68.png --full True -f MTX/barrier2-11.mtx
#python3 time_entropy_2.py -png  69.png --full True -f MTX/barrier2-10.mtx
#python3 time_entropy_2.py -png  70.png --full True -f MTX/barrier2-9.mtx
#python3 time_entropy_2.py -png  71.png --full True -f MTX/shipsec8.mtx
#python3 time_entropy_2.py -png  72.png --full True -f MTX/Ga10As10H30.mtx
#python3 time_entropy_2.py -png  73.png --full True -f MTX/barrier2-1.mtx
#python3 time_entropy_2.py -png  74.png --full True -f MTX/barrier2-4.mtx
#python3 time_entropy_2.py -png  75.png --full True -f MTX/barrier2-3.mtx
#python3 time_entropy_2.py -png  76.png --full True -f MTX/barrier2-2.mtx
#python3 time_entropy_2.py -png  77.png --full True -f MTX/Ge99H100.mtx
#python3 time_entropy_2.py -png  78.png --full True -f MTX/Ge87H76.mtx
#python3 time_entropy_2.py -png  79.png --full True -f MTX/Baumann.mtx
#python3 time_entropy_2.py -png  80.png --full True -f MTX/rajat23.mtx
#python3 time_entropy_2.py -png  81.png --full True -f MTX/lung2.mtx
#python3 time_entropy_2.py -png  82.png --full True -f MTX/x104.mtx
#python3 time_entropy_2.py -png  83.png --full True -f MTX/filter3D.mtx
#python3 time_entropy_2.py -png  84.png --full True -f MTX/hcircuit.mtx
#python3 time_entropy_2.py -png  85.png --full True -f MTX/matrix_9.mtx
#python3 time_entropy_2.py -png  86.png --full True -f MTX/thermomech_TK.mtx
#python3 time_entropy_2.py -png  87.png --full True -f MTX/thermomech_TC.mtx
#python3 time_entropy_2.py -png  88.png --full True -f MTX/2cubes_sphere.mtx
#python3 time_entropy_2.py -png  89.png --full True -f MTX/ASIC_100k.mtx
#python3 time_entropy_2.py -png  90.png --full True -f MTX/ASIC_100ks.mtx
#python3 time_entropy_2.py -png  91.png --full True -f MTX/m_t1.mtx
#python3 time_entropy_2.py -png  92.png --full True -f MTX/Si34H36.mtx
#python3 time_entropy_2.py -png  93.png --full True -f MTX/rajat17.mtx
#python3 time_entropy_2.py -png  94.png --full True -f MTX/rajat16.mtx
#python3 time_entropy_2.py -png  95.png --full True -f MTX/rajat18.mtx
#python3 time_entropy_2.py -png  96.png --full True -f MTX/boyd1.mtx
#python3 time_entropy_2.py -png  97.png --full True -f MTX/s3dkq4m2.mtx
#python3 time_entropy_2.py -png  98.png --full True -f MTX/s3dkt3m2.mtx
#python3 time_entropy_2.py -png  99.png --full True -f MTX/denormal.mtx
#python3 time_entropy_2.py -png 100.png --full True -f MTX/olesnik0.mtx
#python3 time_entropy_2.py -png 101.png --full True -f MTX/ncvxqp7.mtx
#python3 time_entropy_2.py -png 102.png --full True -f MTX/rajat25.mtx
#python3 time_entropy_2.py -png 103.png --full True -f MTX/rajat28.mtx
#python3 time_entropy_2.py -png 104.png --full True -f MTX/rajat20.mtx
#python3 time_entropy_2.py -png 105.png --full True -f MTX/poisson3Db.mtx
#python3 time_entropy_2.py -png 106.png --full True -f MTX/epb3.mtx
#python3 time_entropy_2.py -png 107.png --full True -f MTX/TSOPF_FS_b300_c3.mtx
#python3 time_entropy_2.py -png 108.png --full True -f MTX/c-72.mtx
#python3 time_entropy_2.py -png 109.png --full True -f MTX/consph.mtx
#python3 time_entropy_2.py -png 110.png --full True -f MTX/thermal1.mtx
#python3 time_entropy_2.py -png 111.png --full True -f MTX/shallow_water2.mtx
#python3 time_entropy_2.py -png 112.png --full True -f MTX/shallow_water1.mtx
#python3 time_entropy_2.py -png 113.png --full True -f MTX/apache1.mtx
#python3 time_entropy_2.py -png 114.png --full True -f MTX/cont-201.mtx
#python3 time_entropy_2.py -png 115.png --full True -f MTX/circuit_4.mtx
#python3 time_entropy_2.py -png 116.png --full True -f MTX/a2nnsnsl.mtx
#python3 time_entropy_2.py -png 117.png --full True -f MTX/a0nsdsil.mtx
#python3 time_entropy_2.py -png 118.png --full True -f MTX/rail_79841.mtx
#python3 time_entropy_2.py -png 119.png --full True -f MTX/t3dh.mtx
#python3 time_entropy_2.py -png 120.png --full True -f MTX/t3dh_a.mtx
#python3 time_entropy_2.py -png 121.png --full True -f MTX/t3dh_e.mtx
#python3 time_entropy_2.py -png 122.png --full True -f MTX/c-71.mtx
#python3 time_entropy_2.py -png 123.png --full True -f MTX/shyy161.mtx
#python3 time_entropy_2.py -png 124.png --full True -f MTX/TSOPF_FS_b39_c19.mtx
#python3 time_entropy_2.py -png 125.png --full True -f MTX/ncvxqp3.mtx
#python3 time_entropy_2.py -png 126.png --full True -f MTX/finan512.mtx
#python3 time_entropy_2.py -png 127.png --full True -f MTX/oilpan.mtx
#python3 time_entropy_2.py -png 128.png --full True -f MTX/tomographic1.mtx
#python3 time_entropy_2.py -png 129.png --full True -f MTX/nd24k.mtx
#python3 time_entropy_2.py -png 130.png --full True -f MTX/landmark.mtx
#python3 time_entropy_2.py -png 131.png --full True -f MTX/F2.mtx
#python3 time_entropy_2.py -png 132.png --full True -f MTX/cfd1.mtx
#python3 time_entropy_2.py -png 133.png --full True -f MTX/lhr71.mtx
#python3 time_entropy_2.py -png 134.png --full True -f MTX/lhr71c.mtx
#python3 time_entropy_2.py -png 135.png --full True -f MTX/c-70.mtx
#python3 time_entropy_2.py -png 136.png --full True -f MTX/bcircuit.mtx
#python3 time_entropy_2.py -png 137.png --full True -f MTX/deltaX.mtx
#python3 time_entropy_2.py -png 138.png --full True -f MTX/Chebyshev4.mtx
#python3 time_entropy_2.py -png 139.png --full True -f MTX/k1_san.mtx
#python3 time_entropy_2.py -png 140.png --full True -f MTX/c-69.mtx
#python3 time_entropy_2.py -png 141.png --full True -f MTX/laminar_duct3D.mtx
#python3 time_entropy_2.py -png 142.png --full True -f MTX/H2O.mtx
#python3 time_entropy_2.py -png 143.png --full True -f MTX/gas_sensor.mtx
#python3 time_entropy_2.py -png 144.png --full True -f MTX/stormg2-125.mtx
#python3 time_entropy_2.py -png 145.png --full True -f MTX/qa8fm.mtx
#python3 time_entropy_2.py -png 146.png --full True -f MTX/qa8fk.mtx
#python3 time_entropy_2.py -png 147.png --full True -f MTX/mri1.mtx
#python3 time_entropy_2.py -png 148.png --full True -f MTX/Dubcova2.mtx
#python3 time_entropy_2.py -png 149.png --full True -f MTX/c-68.mtx
#python3 time_entropy_2.py -png 150.png --full True -f MTX/mark3jac140.mtx
#python3 time_entropy_2.py -png 151.png --full True -f MTX/mark3jac140sc.mtx
#python3 time_entropy_2.py -png 152.png --full True -f MTX/crankseg_2.mtx
#python3 time_entropy_2.py -png 153.png --full True -f MTX/mri2.mtx
#python3 time_entropy_2.py -png 154.png --full True -f MTX/ncvxqp5.mtx
#python3 time_entropy_2.py -png 155.png --full True -f MTX/cant.mtx
#python3 time_entropy_2.py -png 156.png --full True -f MTX/venkat25.mtx
#python3 time_entropy_2.py -png 157.png --full True -f MTX/venkat01.mtx
#python3 time_entropy_2.py -png 158.png --full True -f MTX/venkat50.mtx
#python3 time_entropy_2.py -png 159.png --full True -f MTX/Ga3As3H12.mtx
#python3 time_entropy_2.py -png 160.png --full True -f MTX/GaAsH6.mtx
#python3 time_entropy_2.py -png 161.png --full True -f MTX/water_tank.mtx
#python3 time_entropy_2.py -png 162.png --full True -f MTX/TSOPF_RS_b39_c30.mtx
#python3 time_entropy_2.py -png 163.png --full True -f MTX/blockqp1.mtx
#python3 time_entropy_2.py -png 164.png --full True -f MTX/a5esindl.mtx
#python3 time_entropy_2.py -png 165.png --full True -f MTX/dixmaanl.mtx
#python3 time_entropy_2.py -png 166.png --full True -f MTX/g7jac200.mtx
#python3 time_entropy_2.py -png 167.png --full True -f MTX/g7jac200sc.mtx
#python3 time_entropy_2.py -png 168.png --full True -f MTX/c-67b.mtx
#python3 time_entropy_2.py -png 169.png --full True -f MTX/c-67.mtx
#python3 time_entropy_2.py -png 170.png --full True -f MTX/bayer01.mtx
#python3 time_entropy_2.py -png 171.png --full True -f MTX/TSOPF_FS_b300_c2.mtx
#python3 time_entropy_2.py -png 172.png --full True -f MTX/copter2.mtx
#python3 time_entropy_2.py -png 173.png --full True -f MTX/mark3jac120sc.mtx
#python3 time_entropy_2.py -png 174.png --full True -f MTX/mark3jac120.mtx
#python3 time_entropy_2.py -png 175.png --full True -f MTX/nasasrb.mtx
#python3 time_entropy_2.py -png 176.png --full True -f MTX/2D_54019_highK.mtx
#python3 time_entropy_2.py -png 177.png --full True -f MTX/g7jac180.mtx
#python3 time_entropy_2.py -png 178.png --full True -f MTX/g7jac180sc.mtx
#python3 time_entropy_2.py -png 179.png --full True -f MTX/crankseg_1.mtx
#python3 time_entropy_2.py -png 180.png --full True -f MTX/ct20stif.mtx
#python3 time_entropy_2.py -png 181.png --full True -f MTX/ecl32.mtx
#python3 time_entropy_2.py -png 182.png --full True -f MTX/dawson5.mtx
#python3 time_entropy_2.py -png 183.png --full True -f MTX/ibm_matrix_2.mtx
#python3 time_entropy_2.py -png 184.png --full True -f MTX/3D_51448_3D.mtx
#python3 time_entropy_2.py -png 185.png --full True -f MTX/c-64.mtx
#python3 time_entropy_2.py -png 186.png --full True -f MTX/c-64b.mtx
#python3 time_entropy_2.py -png 187.png --full True -f MTX/rajat26.mtx
#python3 time_entropy_2.py -png 188.png --full True -f MTX/cvxbqp1.mtx
#python3 time_entropy_2.py -png 189.png --full True -f MTX/ncvxbqp1.mtx
#python3 time_entropy_2.py -png 190.png --full True -f MTX/sparsine.mtx
#python3 time_entropy_2.py -png 191.png --full True -f MTX/c-66b.mtx
#python3 time_entropy_2.py -png 192.png --full True -f MTX/c-66.mtx
#python3 time_entropy_2.py -png 193.png --full True -f MTX/ckt11752_dc_1.mtx
#python3 time_entropy_2.py -png 194.png --full True -f MTX/ckt11752_tr_0.mtx
#python3 time_entropy_2.py -png 195.png --full True -f MTX/stokes128.mtx
#python3 time_entropy_2.py -png 196.png --full True -f MTX/gridgena.mtx
#python3 time_entropy_2.py -png 197.png --full True -f MTX/xenon1.mtx
#python3 time_entropy_2.py -png 198.png --full True -f MTX/fome13.mtx
#python3 time_entropy_2.py -png 199.png --full True -f MTX/c-65.mtx
#python3 time_entropy_2.py -png 200.png --full True -f MTX/g7jac160.mtx
#python3 time_entropy_2.py -png 201.png --full True -f MTX/g7jac160sc.mtx
#python3 time_entropy_2.py -png 202.png --full True -f MTX/vanbody.mtx
#python3 time_entropy_2.py -png 203.png --full True -f MTX/Maragal_7.mtx
#python3 time_entropy_2.py -png 204.png --full True -f MTX/rma10.mtx
#python3 time_entropy_2.py -png 205.png --full True -f MTX/bcsstk39.mtx
#python3 time_entropy_2.py -png 206.png --full True -f MTX/karted.mtx
#python3 time_entropy_2.py -png 207.png --full True -f MTX/mark3jac100.mtx
#python3 time_entropy_2.py -png 208.png --full True -f MTX/mark3jac100sc.mtx
#python3 time_entropy_2.py -png 209.png --full True -f MTX/mouse_gene.mtx
#python3 time_entropy_2.py -png 210.png --full True -f MTX/c-63.mtx
#python3 time_entropy_2.py -png 211.png --full True -f MTX/OPF_10000.mtx
#python3 time_entropy_2.py -png 212.png --full True -f MTX/c-60.mtx
#python3 time_entropy_2.py -png 213.png --full True -f MTX/c-61.mtx
#python3 time_entropy_2.py -png 214.png --full True -f MTX/sme3Dc.mtx
#python3 time_entropy_2.py -png 215.png --full True -f MTX/TSOPF_RS_b300_c3.mtx
#python3 time_entropy_2.py -png 216.png --full True -f MTX/c-62.mtx
#python3 time_entropy_2.py -png 217.png --full True -f MTX/c-62ghs.mtx
#python3 time_entropy_2.py -png 218.png --full True -f MTX/g7jac140.mtx
#python3 time_entropy_2.py -png 219.png --full True -f MTX/g7jac140sc.mtx
#python3 time_entropy_2.py -png 220.png --full True -f MTX/jan99jac120sc.mtx
#python3 time_entropy_2.py -png 221.png --full True -f MTX/jan99jac120.mtx
#python3 time_entropy_2.py -png 222.png --full True -f MTX/fxm3_16.mtx
#python3 time_entropy_2.py -png 223.png --full True -f MTX/c-59.mtx
#python3 time_entropy_2.py -png 224.png --full True -f MTX/av41092.mtx
#python3 time_entropy_2.py -png 225.png --full True -f MTX/minsurfo.mtx
#python3 time_entropy_2.py -png 226.png --full True -f MTX/TSOPF_FS_b162_c4.mtx
#python3 time_entropy_2.py -png 227.png --full True -f MTX/cond-mat-2005.mtx
#python3 time_entropy_2.py -png 228.png --full True -f MTX/chem_master1.mtx
#python3 time_entropy_2.py -png 229.png --full True -f MTX/bauru5727.mtx
#python3 time_entropy_2.py -png 230.png --full True -f MTX/juba40k.mtx
#python3 time_entropy_2.py -png 231.png --full True -f MTX/case39.mtx
#python3 time_entropy_2.py -png 232.png --full True -f MTX/jnlbrng1.mtx
#python3 time_entropy_2.py -png 233.png --full True -f MTX/obstclae.mtx
#python3 time_entropy_2.py -png 234.png --full True -f MTX/torsion1.mtx
#python3 time_entropy_2.py -png 235.png --full True -f MTX/rajat22.mtx
#python3 time_entropy_2.py -png 236.png --full True -f MTX/cage11.mtx
#python3 time_entropy_2.py -png 237.png --full True -f MTX/bbmat.mtx
#python3 time_entropy_2.py -png 238.png --full True -f MTX/mario001.mtx
#python3 time_entropy_2.py -png 239.png --full True -f MTX/TSOPF_RS_b2383.mtx
#python3 time_entropy_2.py -png 240.png --full True -f MTX/TSOPF_RS_b2383_c1.mtx
#python3 time_entropy_2.py -png 241.png --full True -f MTX/TSOPF_RS_b39_c19.mtx
#python3 time_entropy_2.py -png 242.png --full True -f MTX/scfxm1-2r.mtx
#python3 time_entropy_2.py -png 243.png --full True -f MTX/c-57.mtx
#python3 time_entropy_2.py -png 244.png --full True -f MTX/viscorocks.mtx
#python3 time_entropy_2.py -png 245.png --full True -f MTX/c-58.mtx
#python3 time_entropy_2.py -png 246.png --full True -f MTX/rajat15.mtx
#python3 time_entropy_2.py -png 247.png --full True -f MTX/mark3jac080.mtx
#python3 time_entropy_2.py -png 248.png --full True -f MTX/mark3jac080sc.mtx
#python3 time_entropy_2.py -png 249.png --full True -f MTX/wathen120.mtx
#python3 time_entropy_2.py -png 250.png --full True -f MTX/pdb1HYS.mtx
				
				
